#!/bin/bash
echo "Criado por Jesus Leal - contato@sysoplinux.com.br"
#### Este script pode ser alterado, editado mas pessoal se puder manter os créditos hehe :)
#### Espero que este script seja útil para você!!
# Capturar IP usando o curl -s
# Criar o diretorio IPlog
mkdir -p /tmp/IPlog
# Local para savar os LOGs
PATH_LOG='/tmp/IPlog'
# LOG com data e hora
LOG=`date +%F_%R_`
curl -s 'http://www.myip.net/judge.php' | grep 'REMOTE_ADDR' | cut -f2 -d '=' | sed 's/^ \+//' >> "$PATH_LOG/IP_em_$LOG.txt"
